name: CI-OSX

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:

  build:
    runs-on: macos-latest
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
         cmake-version: '3.16.x'

      - name: Test
        run: go test -v ./db ./substate

